version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install -g typescript
            - npm install
    pre_build:
        commands:
            - echo Pre-Build started on `date`
            - npm run build-files
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
cache:
    paths:
        - "node_modules/**/*"
artifacts:
    files:
        - "**/*"
    base-directory: "dist"
    name: leadoff-portal-backend-$(date +%Y-%m-%d)
